name: Pvptoggle
version: '${project.version}'
main: benkralex.pvptoggle.Pvptoggle
api-version: 1.20
depend: [CommandAPI]
permissions:
  pvp.toggle:
    default: true
  pvp.ultra:
    default: true
  pvp.trust:
    default: true
  pvp.misstrust:
    default: true
  pvp.inv.normal:
    default: true
  pvp.inv.op:
    default: op
