name: Pvptoggle
version: '1.6-FINAL'
main: benkralex.pvptoggle.Pvptoggle
author:
  -Benkralex
  -skippyall
api-version: 1.20
depend:
- CommandAPI
permissions:
  pvp.toggle:
    default: true
  pvp.ultra:
    default: true
  pvp.whitelist:
    default: true
  pvp.blacklist:
    default: true
  pvp.inv.normal:
    default: true
  pvp.inv.op:
    default: op
  pvp.fight:
    default: true
